package edu.weber.resptherapy.charting.model;
// Generated Oct 15, 2016 12:14:38 AM by Hibernate Tools 4.3.1



/**
 * Formtemplate generated by hbm2java
 */
public class Formtemplate implements java.io.Serializable {


     private Integer formTemplateId;
     private String formTemplateName;
     private String formTemplateHtml;
     private String formTemplateType;
     private Boolean formTemplateActive;
     private Integer formTemplateVersionNum;

    public Formtemplate() {
    }

	
    public Formtemplate(String formTemplateName) {
        this.formTemplateName = formTemplateName;
    }
    public Formtemplate(String formTemplateName, String formTemplateHtml, String formTemplateType, Boolean formTemplateActive, Integer formTemplateVersionNum) {
       this.formTemplateName = formTemplateName;
       this.formTemplateHtml = formTemplateHtml;
       this.formTemplateType = formTemplateType;
       this.formTemplateActive = formTemplateActive;
       this.formTemplateVersionNum = formTemplateVersionNum;
    }
   
    public Integer getFormTemplateId() {
        return this.formTemplateId;
    }
    
    public void setFormTemplateId(Integer formTemplateId) {
        this.formTemplateId = formTemplateId;
    }
    public String getFormTemplateName() {
        return this.formTemplateName;
    }
    
    public void setFormTemplateName(String formTemplateName) {
        this.formTemplateName = formTemplateName;
    }
    public String getFormTemplateHtml() {
        return this.formTemplateHtml;
    }
    
    public void setFormTemplateHtml(String formTemplateHtml) {
        this.formTemplateHtml = formTemplateHtml;
    }
    public String getFormTemplateType() {
        return this.formTemplateType;
    }
    
    public void setFormTemplateType(String formTemplateType) {
        this.formTemplateType = formTemplateType;
    }
    public Boolean getFormTemplateActive() {
        return this.formTemplateActive;
    }
    
    public void setFormTemplateActive(Boolean formTemplateActive) {
        this.formTemplateActive = formTemplateActive;
    }
    public Integer getFormTemplateVersionNum() {
        return this.formTemplateVersionNum;
    }
    
    public void setFormTemplateVersionNum(Integer formTemplateVersionNum) {
        this.formTemplateVersionNum = formTemplateVersionNum;
    }




}


