package edu.weber.resptherapy.charting.model;
// Generated Oct 15, 2016 12:14:38 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Userform generated by hbm2java
 */
public class Userform  implements java.io.Serializable {


     private Integer userFormId;
     private User user;
     private String formTemplateHtml;
     private String userFormName;
     private Date userFormLastEdit;

    public Userform() {
    }

	
    public Userform(User user, String userFormName, Date userFormLastEdit) {
        this.user = user;
        this.userFormName = userFormName;
        this.userFormLastEdit = userFormLastEdit;
    }
    public Userform(User user, String formTemplateHtml, String userFormName, Date userFormLastEdit) {
       this.user = user;
       this.formTemplateHtml = formTemplateHtml;
       this.userFormName = userFormName;
       this.userFormLastEdit = userFormLastEdit;
    }
   
    public Integer getUserFormId() {
        return this.userFormId;
    }
    
    public void setUserFormId(Integer userFormId) {
        this.userFormId = userFormId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getFormTemplateHtml() {
        return this.formTemplateHtml;
    }
    
    public void setFormTemplateHtml(String formTemplateHtml) {
        this.formTemplateHtml = formTemplateHtml;
    }
    public String getUserFormName() {
        return this.userFormName;
    }
    
    public void setUserFormName(String userFormName) {
        this.userFormName = userFormName;
    }
    public Date getUserFormLastEdit() {
        return this.userFormLastEdit;
    }
    
    public void setUserFormLastEdit(Date userFormLastEdit) {
        this.userFormLastEdit = userFormLastEdit;
    }




}


